### ISSUE TITLE
Suivre une trajectoire courbe

### ISSUE THREAD

**Issue by LateAlways** [Ultime5528/FRC2024#7]
Qu'est-ce que wpilib fournit pour les trajectoires de swerve? Est-ce qu'on pourrait l'adapter, pour, par exemple, mettre de faux headings pour créer une courbe et se fier aux (x, y) ?

Autre possibilité : [PathPlanner](https://github.com/mjansen4857/pathplanner) + [PathPlannerLib](https://robotpy.readthedocs.io/projects/pathplannerlib/en/stable/api.html)
```[tasklist]
### Tasks
```

**Comment by LaMaudite** [comment]
On devrait s'assurer que si le robot est dévié de sa course par un obstacle (autre robot par exemple), alors il se rend quand même au point demandé.
