### ISSUE TITLE
Switch ajouter états inutilisés

### ISSUE THREAD

**Issue by etiennebeaulac** [Ultime5528/FRC2024#75]
Pour des switchs qui sont en réalité inutilisés, ajouter des états qui retournent always pressed true et le contraire (par exemple, pour les switchs du bas des climbers)

**Comment by LaMaudite** [comment]
Plus j'y pense, plus je suspecte que c'est une fausse bonne idée ;-)

- Si on a une Switch qui est inutilisée, alors on devrait la remplacer par une qui est "always pressed" ou "always unpressed".
- Mais la logique du système et des commandes ne pourrait plus utiliser cette switch pour prendre des décisions
- On finirait donc par l'enlever du code de toute façon
- Le but était de ne pas changer le code qui utilisait la Switch, mais on finit par le modifier quand même pour des raisons algorithmiques.
- C'est sans compter que d'avoir une Switch bidon pourrait introduire des bugs parce que les comportements de la simulation et du vrai robot ne serait plus identiques.

Comme le code est dans git, je pense qu'on devrait simplement enlever les switches qui n'existent plus. Ça serait plus safe et plus correct. Et si jamais elle revient, alors on regarde dans git pour la remettre comme elle était.
